name: Multi-Arch Golang UPX CI

on:
  push:
    branches: [1.23.1-bookworm]
  pull_request:
    branches: [1.23.1-bookworm]
  workflow_dispatch:

jobs:
  build:
    name: Build multi-arch image
    runs-on: ${{ vars.RUNNER_OS }}
    if: contains(github.event.head_commit.message, '#build') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: "image=moby/buildkit:master"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Extract repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_OUTPUT

      - name: Extract branch name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.branch_name.outputs.BRANCH_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
